BUGFIX: Handle AjaxWidgets after SecurityEntryPoint
neos/flow-development-collection pull request #2256
Opened 2020-11-16 22:48 UTC by albe

Otherwise, the security context is not initialized and security would not work but throw an exception (e.g. Neos.Setup)

2020-11-16 23:50 UTC, albe commented
Test failures, see https://github.com/neos/flow-development-collection/pull/2257

2020-11-17 07:23 UTC, kdambekalns approved these changes
Sounds reasonable.

2020-11-17 07:49 UTC, albe commented
Only thing is this is now efffectively a "before dispatch", so this does not shortcut anything like routing or so unless we move the securityEntryPoint way earlier

2020-11-17 08:19 UTC, bwaidelich commented
> unless we move the securityEntryPoint way earlier

But Security requires an `ActionRequest` which is only available after Routing. Or how was that solved before?

2020-11-17 08:22 UTC, albe commented
> But Security requires an ActionRequest which is only available after Routing. Or how was that solved before?

🤔 good question. Looking at it, it seemed to be included "before routing" originally https://github.com/neos/flow-development-collection/blob/6.3/Neos.FluidAdaptor/Configuration/Settings.yaml#L8

2020-11-17 09:12 UTC, bwaidelich requested changes
As discussed: This worked before since the Widget Component created an `ActionRequest` and initialized the Security Context: https://github.com/neos/flow-development-collection/blob/6.3/Neos.FluidAdaptor/Classes/Core/Widget/AjaxWidgetComponent.php#L82-L84

And that makes sense, because the original route is not considered if the widget kicks in

2020-11-17 09:40 UTC, albe commented
👍 approve this rewrite of this change :)

2020-11-17 09:56 UTC, albe commented
`sudo merge` now - the fix is obvious and travis only complained about #2257

2020-11-17 09:56 UTC, merged