TASK: Restore output of executed SQL during doctrine:migrate
neos/flow-development-collection pull request #2328
Opened 2020-12-08 10:39 UTC by kdambekalns

See https://github.com/neos/flow-development-collection/issues/2244

2020-12-08 11:47 UTC, bwaidelich commented on Neos.Flow/Classes/Persistence/Doctrine/Service.php
> +    protected BufferedOutput $logMessages;
This ain't PHP 7.3 compatible, is it?

2020-12-08 11:49 UTC, bwaidelich requested changes
Great improvement!
But PHP 7.3 doesn't yet support type hints for properties I think

2020-12-08 11:50 UTC, bwaidelich commented on Neos.Flow/Classes/Persistence/Doctrine/Service.php
> +    protected BufferedOutput $logMessages;
```suggestion
    protected $logMessages;
```

2020-12-08 11:51 UTC, bwaidelich approved these changes
Great (by reading)
Will test asap if it doesn't get merged before :)

2020-12-09 07:27 UTC, kdambekalns commented
Uhm… the Behat tests fail with

`PHP Fatal error:  Declaration of Symfony\Component\Console\Output\BufferedOutput::doWrite(string $message, bool $newline) must be compatible with Symfony\Component\Console\Output\Output::doWrite($message, $newline) in /home/travis/build/neos/flow-development-distribution/Packages/Libraries/symfony/console/Output/BufferedOutput.php on line 45`

🤔

2020-12-09 07:33 UTC, kdambekalns commented
Probably caused by Behat using Console v4.2.2 vs the 5.2.0 Flow installs.

2020-12-09 07:46 UTC, kdambekalns commented
Opened https://github.com/neos/behat/issues/21

2020-12-09 08:10 UTC, kdambekalns commented
https://github.com/neos/behat/pull/22

2020-12-09 09:53 UTC, bwaidelich commented
@kdambekalns thanks! with neos/behat#21 resolved should I trigger a rebuild?

2020-12-09 11:11 UTC, kdambekalns commented
First Behat passes, second now running. Static analysis failing unrelated on a changed constant…

2020-12-09 11:50 UTC, albe reviewed
Looks good now (tests green)

2020-12-09 12:00 UTC, bwaidelich approved these changes
I just tweaked this a tiny bit by extracting the version normalization into its dedicated method to reduce duplication.
Still experiencing bugs but not related to this PR

2020-12-09 12:00 UTC, merged