DX: Make backtrace code expandable with HTML5 <summary> element
neos/flow-development-collection pull request #2368
Opened 2020-12-31 10:26 UTC by sorenmalling

The backtrace code is printed when the DebugExceptionHandler is active (in "Development" context).

This can be queit a mouthful for new users and developers. The backtrace go all the way back to the Flow Bootstrapping - things that are interesting when you get more into Flow.

This is changed, by using the HTML5 element `<summary>` element that support collapsing without any extra libraries or code

Resolves: #2367

2021-01-01 19:41 UTC, jonnitto approved these changes
Small change, but a huge impact on the developer experience! Thanks a lot, @sorenmalling; great idea! ❤️

2021-01-02 06:44 UTC, daniellienert requested changes
I am really unsure about this change as I think it does not improve the experience. 

-  As an experienced developer I now have an additional klick every time a get an error message to see the stack trace
- New developers are already lost with the information above the stack trace.
- The toggle for the backtrace is rather small compared to other visual elements of the error message and can be easily overlooked

2021-01-03 22:37 UTC, sorenmalling commented
> -  As an experienced developer I now have an additional klick every time I get an error message to see the stack trace

Is that because the exception that we bring with Flow is not usefully "low-quality", that this extra click is a issue? 
If so and we can agree upon, we ca  create a umbrella issue for working on that - that will bring better development experience for sure 😍

> - New developers are already lost with the information above the stack trace.

Where does this conclusion come from? Because of low-quality exception messages? Experience with new developers at work? And is that comment a pro or cons of the proposed change?


> - The toggle for the backtrace is rather small compared to other visual elements of the error message and can be easily overlooked

We talk about the visual of the "toggle" - so that means that you like the idea, despite above comments? 🤩

2021-01-12 07:48 UTC, sorenmalling commented
ping @daniellienert

2021-02-01 16:12 UTC, sorenmalling commented
ping @daniellienert

2021-03-08 09:40 UTC, sorenmalling commented
ping @albe care to consider this for 7.1 or if it should be rejected?

2021-03-08 23:40 UTC, albe commented
I do think this makes the first look on the exception page quite a bit less overwhelming, so 👍 for that. But I also do see the points that Daniel makes - especially in a relatively tight debug cycles with "edit code, reload, check exception stack trace, repeat" having to click again and again can become a nuisance. Not sure if that is more important than not overwhelming in the first place. And yes, let's make the backtrace toggle slightly larger and/or use the white font on dark blue color as for each stack trace method headline.

I'd not veto this and maybe we can somehow convince Daniel that having to click the toggle is not quite as bad?

2021-05-11 07:19 UTC, sorenmalling commented
@mficzel sounds superb 👍

2021-11-17 10:35 UTC, sorenmalling commented
@daniellienert @mficzel @albe 

Idea came up today:

 - Per default, the stack trace is "hidden".
 - If you expand it, we set a localStorage item like "Flow_Exception_Backtrace_Expanded" = true
 - If this is set, it's expanded by default and can be toggled.

All possible with vanilla js and no requirement from outside libraries

2021-11-26 21:49 UTC, mhsdesign commented
as im relatively new to neos i remember that these messages where a long time so overwehlming, that i didnt even really read the exception message. So i would love a more structured less bloated design which is more beginner friendly. (and maybe even more appealing ^^ )

(i do kind of agree with daniel on 'New developers are already lost with the information above the stack trace.' ;) - own experience ^^)

2021-11-27 01:03 UTC, jonnitto commented
> @daniellienert @mficzel @albe
> 
> Idea came up today:
> 
> * Per default, the stack trace is "hidden".
> * If you expand it, we set a localStorage item like "Flow_Exception_Backtrace_Expanded" = true
> * If this is set, it's expanded by default and can be toggled.
> 
> All possible with vanilla js and no requirement from outside libraries

@sorenmalling will you finish this feature before we branch for 7.3? Because I would also like to have it as you described

2021-11-27 14:58 UTC, sorenmalling commented
> > @daniellienert @mficzel @albe
> > Idea came up today:
> > 
> > * Per default, the stack trace is "hidden".
> > * If you expand it, we set a localStorage item like "Flow_Exception_Backtrace_Expanded" = true
> > * If this is set, it's expanded by default and can be toggled.
> > 
> > All possible with vanilla js and no requirement from outside libraries
> 
> @sorenmalling will you finish this feature before we branch for 7.3? Because I would also like to have it as you described

Yes, I will give it a go Monday 👍

2021-11-29 07:47 UTC, sorenmalling commented
ping all involved :)
Videos show the implementation of localStorage

By default it's closed
If you open, it will open on next request
If you close again, it will be closed on next request

https://user-images.githubusercontent.com/531918/143827853-fad892b7-cbad-4555-ba98-f20909cde4a5.mov

2021-11-29 09:58 UTC, sorenmalling commented
> I do not strongly disagree - it really seems valuable to others

@daniellienert I hope this solution can be useful for your workflow as well 💙

2021-11-30 22:33 UTC, markusguenther commented on Neos.Flow/Resources/Public/Error/Exception.js
> +let localStorageItemIdentifier = 'Flow-Debug-Exception-Backtrace-Code-Open';
This could be a `const`, as we don't modify the values

2021-11-30 22:39 UTC, markusguenther approved these changes
I can understand the concerns of @daniellienert, but in general, I like the change.
Just had a tiny comment in the JS and the Psalm issue seems to be unrelated :)

Thanks Søren 💙

2021-12-01 11:45 UTC, jonnitto approved these changes
Just a small code cleanup…

2021-12-01 11:45 UTC, jonnitto commented on Neos.Flow/Resources/Public/Error/Exception.css
> +
```suggestion
.Flow-Debug-Exception-Backtrace-Code {
    background: #fff;
    color: #656a71;
    padding: 5px;
}

.Flow-Debug-Exception-Backtrace-Code summary{
    cursor: pointer;
}

```

2021-12-01 11:45 UTC, jonnitto commented on Neos.Flow/Resources/Public/Error/Exception.css
> +
Just a bit code cleanup ;-)

2021-12-02 13:55 UTC, merged