BUGFIX: #2696 Web-Exception messages, preserve whitespace (ASCII Art)
neos/flow-development-collection pull request #2697
Opened 2022-02-06 22:22 UTC by mhsdesign

Closes #2696

Exceptions which have multiple spaces in their $message where previously not as expected displayed.
Exceptions outputted to the CLI or logged did preserve multiple whitespaces naturally, but since they are collapsed in HTML by default, they are not shown in the browser.

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

2022-02-11 11:35 UTC, albe approved these changes
Generally approve, but should we maybe just always use `pre` formatting for the body?

2022-02-11 14:09 UTC, mhsdesign commented
hmm could potentially harm readability - what do you think? But is also easy to change later again when its not ideal.

2022-03-11 09:16 UTC, bwaidelich requested changes, later dismissed
I think it it is a bit flaky to change the formatting based on some characters in the exception message.. So +1 with what Alex wrote (given that we can keep it readable for both worlds)

2022-03-11 09:16 UTC, bwaidelich commented on Neos.Flow/Classes/Error/DebugExceptionHandler.php
> +                if (strpos($exceptionMessagePartBody, '  ') !== false) {
ooh that's hacky ;)
I'd go for a unified rendering, too.

2022-03-11 09:19 UTC, bwaidelich commented
If using monospace font and `white-space: pre` in general leads to problems with readability, we could maybe introduce another (optional) property to the Flow exception base class that allows to render formatted strings (similar to `statusCode`)

2022-03-11 13:01 UTC, mhsdesign commented
i thought about additional optional properties on the exception too - but we took already a way different way - the 'a let flow handle this all automatic way':
for example the exception message is splitt by some hacky regex into head and body:
here and this is not configureable:
https://github.com/neos/flow-development-collection/blob/0a19f923d959f6bc34ec61bc5ba7b673ed5478a3/Neos.Flow/Classes/Error/AbstractExceptionHandler.php#L338

i think then we should rather refactor the whole exception handling part and not introduce only a random `wrapInPre` option ...

2022-03-11 13:46 UTC, kitsunet commented
I wonder if we can't scoop a good solution eg. from symfony or whoops or so.

2022-03-28 08:17 UTC, kdambekalns approved these changes
I think that's fine, rather preserve formatting and risk readability than reverse. And we can change it, if it really becomes an issue.

2024-02-03 10:48 UTC, mhsdesign commented
@bwaidelich i just rebased this pr and its crazy that its already two years old ;D
I understand your preservations, but think it's okay to fix this as proposed.

2024-02-06 16:34 UTC, merged