BUGFIX: InternalRequestEngine should behave like HttpRequestEngine
neos/flow-development-collection pull request #2854
Opened 2022-06-07 10:17 UTC by fcool

The `HttpRequestEngine` holds a reference to the "current" http request in each step of the middleware chain.
The internal request engine does not, making it hard to write tests, that predict system behavior.

With this patch you can fetch the current request (and not only the outer most) even in `InternalRequestEngine`

See `\Neos\Flow\Http\RequestHandler::handleRequest()`

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [x] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [x] Reviewer - The first section explains the change briefly for change-logs
- [x] Reviewer - Breaking Changes are marked wit `!!!` and have upgrade-instructions

2022-06-07 11:47 UTC, mficzel requested changes
`onStep` and `setHttpRequest` are not defined by the psr interfaces and might not exist at all. I think this should use the actual middleware class as the http request handler

Other than that this mainly mimics the following code from the httprequestHandler and makes total sense to me:
https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Http/RequestHandler.php#L102-L104

2022-06-09 10:38 UTC, fcool commented on Neos.Flow/Classes/Http/Client/InternalRequestEngine.php
>          $middlewaresChain = $objectManager->get(Http\Middleware\MiddlewaresChain::class);
Ah! Now I fully understand.

But are you aware, that those "two" are equivalent?
`Http\Middleware\MiddlewaresChain::class` together with `use Neos\Flow\Http;`  (no leading slash on `Http\...`) points to the flow specific implementation.
So its already crystal clear, that it's OUR implementation

2022-06-22 08:02 UTC, bwaidelich approved these changes
+1 by reading, thanks!

2022-06-22 08:31 UTC, albe approved these changes
Yep, makes sense and should have been there from the start.

2022-06-22 09:05 UTC, merged

2022-06-22 09:05 UTC, fcool commented
Thanks :)