TASK: suggest igbinary extension in composer.json
neos/flow-development-collection pull request #2868
Opened 2022-07-02 08:24 UTC by crydotsnake

Related information:

- https://github.com/neos/neos-development-collection/issues/3765
- https://github.com/neos/neos-development-collection/pull/3808

**Checklist**

- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked wit `!!!` and have upgrade-instructions

2022-07-02 08:27 UTC, mhsdesign approved these changes

2022-08-18 05:47 UTC, kdambekalns approved these changes

2022-08-18 05:51 UTC, kdambekalns requested changes
Reverting my approval… you need to update the collection-level `composer.json` using the `ComposerManifestMerger.php` tool in `Build/BuildEssentials`.

And the suggestion should also be in the `neos/cache` package, since they are sometimes used without Flow…

2022-08-18 06:57 UTC, kitsunet commented
Actually only in the neos/cache package? Because apart from comments and documentation there is zero code reference to redis in neos/flow

2022-08-18 07:03 UTC, kdambekalns commented
> there is zero code reference to redis in neos/flow

Why `redis` - this is about `igbinary`…

2022-11-29 14:55 UTC, kdambekalns approved these changes

2022-11-29 14:55 UTC, merged