!!! TASK: Clean up password hashing strategies
neos/flow-development-collection pull request #2920
Opened 2022-10-10 08:29 UTC by kdambekalns

Cleans up the password hashing strategies shipped with Flow.

**Upgrade instructions**

If you implemented ´PasswordHashingStrategyInterface`, make sure to adjust your implementation to use the added type declarations like in the interface.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [x] Reviewer - Breaking Changes are marked wit `!!!` and have upgrade-instructions

2022-10-10 08:31 UTC, kdambekalns commented
`password_hash()` returns strings with `$2y$` instead of "our" `$2a$` inside. But `password_verify()` decodes "our" hashed BCrypt passwords fine, see https://3v4l.org/L0QnW#v8.1.11

2022-10-10 08:33 UTC, kdambekalns commented
Note: We can of course drop the interface change (or move it to 9.0), but I'd say the risk is low. Who would implement their own hashing strategy? 😇

2022-11-09 07:28 UTC, kdambekalns commented
Ping…

2022-11-30 14:46 UTC, albe approved these changes

2022-12-14 07:21 UTC, kdambekalns commented
@markusguenther (and others), any objections to the interface change?

2022-12-14 09:32 UTC, fcool approved these changes

2022-12-14 11:00 UTC, fcool commented
Ah... hmmm... 
Strictly speaking this would be a breaking change, which might be not appropriate for 8.2 - at least without REALLY good reasons...

What about NOT changing the interface in 8.2 - but do so in 9.0? (Rest of the code can stay as it is, if I see it correctly, as "additional hints" are allowed)

On the other hand... I cannot believe, that this interface has been implemented too often outside the Flow packages themself. And it would be quite easy to be forward compatible. (So I would not say, we absolute cannot merge that into 8.2)

2022-12-14 11:11 UTC, bwaidelich commented
> Strictly speaking this would be a breaking change, which might be not appropriate for 8.2 - at least without REALLY good reasons...

I agree

2023-02-13 06:49 UTC, kitsunet requested changes
Agreed with merging ASAP but without the Interface change.

2023-02-13 06:49 UTC, kitsunet commented on Neos.Flow/Classes/Security/Cryptography/PasswordHashingStrategyInterface.php
> +    public function hashPassword(string $password, string $staticSalt = null): string;
```suggestion
    public function hashPassword($password, $staticSalt = null);
```

2023-02-13 06:49 UTC, kitsunet commented on Neos.Flow/Classes/Security/Cryptography/PasswordHashingStrategyInterface.php
> +    public function validatePassword(string $password, string $hashedPasswordAndSalt, string $staticSalt = null): bool;
```suggestion
    public function validatePassword($password, $hashedPasswordAndSalt, $staticSalt = null);
```

2023-02-13 08:28 UTC, jonnitto approved these changes
Fine by reading

2023-02-13 08:44 UTC, kdambekalns commented
> (Rest of the code can stay as it is, if I see it correctly, as "additional hints" are allowed)

No, as the test results show…

2023-02-13 08:48 UTC, kdambekalns reviewed
Revert remaining changes to methods from interface

2023-02-13 08:48 UTC, kdambekalns commented on Neos.Flow/Classes/Security/Cryptography/BCryptHashingStrategy.php
> +    public function hashPassword(string $password, string $staticSalt = null): string
```suggestion
    public function hashPassword($password, $staticSalt = null)
```

2023-02-13 08:48 UTC, kdambekalns commented on Neos.Flow/Classes/Security/Cryptography/BCryptHashingStrategy.php
> +    public function validatePassword(string $password, string $hashedPasswordAndSalt, string $staticSalt = null): bool
```suggestion
    public function validatePassword($password, $hashedPasswordAndSalt, $staticSalt = null)
```

2023-02-13 08:48 UTC, kdambekalns commented on Neos.Flow/Classes/Security/Cryptography/Pbkdf2HashingStrategy.php
> +    public function hashPassword(string $password, string $staticSalt = null): string
```suggestion
    public function hashPassword($password, $staticSalt = null)
```

2023-02-13 08:48 UTC, kdambekalns commented on Neos.Flow/Classes/Security/Cryptography/Pbkdf2HashingStrategy.php
> +    public function validatePassword(string $password, string $hashedPasswordAndSalt, string $staticSalt = null): bool
```suggestion
    public function validatePassword($password, $hashedPasswordAndSalt, $staticSalt = null)
```

2023-02-13 08:48 UTC, kdambekalns commented on Neos.Flow/Tests/Unit/Security/Cryptography/Fixture/TestHashingStrategy.php
> +    public function hashPassword(string $password, string $staticSalt = null): string
```suggestion
    public function hashPassword($password, $staticSalt = null)
```

2023-02-13 08:48 UTC, kdambekalns commented on Neos.Flow/Tests/Unit/Security/Cryptography/Fixture/TestHashingStrategy.php
> +    public function validatePassword(string $password, string $hashedPasswordAndSalt, string $staticSalt = null): bool
```suggestion
    public function validatePassword($password, $hashedPasswordAndSalt, $staticSalt = null)
```

2023-02-13 09:12 UTC, kitsunet commented
Unfortunate :/ But then lets merge this as is now.

2023-02-13 09:13 UTC, kitsunet approved these changes

2023-02-13 09:13 UTC, merged