FEATURE: Add `getDebugType` to Type EelHelper
neos/flow-development-collection pull request #3011
Opened 2023-04-05 09:30 UTC by mficzel

As `php get_debug_type` this returns the classname for objects and otherwise the type of the value.

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked wit `!!!` and have upgrade-instructions

2023-04-05 09:31 UTC, mficzel commented
No tests because this is really trivial.

2023-04-05 10:12 UTC, mhsdesign requested changes
I would opt in for a Debug helper with also a vardump method

2023-04-05 10:18 UTC, mhsdesign commented
like this: https://github.com/PackageFactory/PackageFactory.Fusion.Debug/blob/7a64fa40a84b00f5fd46a0526ef2d384cee172cd/Classes/Debug.php#L17


```

${Debug.var_dump(var).die()}

${Debug.type(var)}

```

2023-04-05 10:28 UTC, mficzel commented
@mhsdesign the TypeHelper already has methods "getType", "typeof" and "className" that is why i simply extended it. Naming may not be optimal yet.

2023-04-05 10:34 UTC, mhsdesign commented
okay well makes sense as well ;)

Then wed only need one line documentation and ill put my green stamp on it ^^

2023-04-05 10:42 UTC, mficzel commented
@mhsdesign The documentation https://neos.readthedocs.io/en/stable/References/EelHelpersReference.html#type is autogenerated by jenkins. Would expect this to show up there magically.

2023-04-05 11:27 UTC, mhsdesign approved these changes

2023-04-11 10:07 UTC, markusguenther approved these changes

2023-04-11 10:31 UTC, crydotsnake approved these changes

2023-04-11 10:58 UTC, merged

2023-04-11 11:11 UTC, markusguenther commented
Psalm is also failing in 8.3 in general :/

https://github.com/neos/flow-development-collection/actions/runs/4583608911