BUGFIX: Fix return type in DocBlock
neos/flow-development-collection pull request #3061
Opened 2023-05-24 15:00 UTC by koehnlein

The return type of `SessionInterface::getData()` was noted as "array", but in fact is "mixed". 

The returned data is the same unchanged data as passed in `putData()` as second parameter, which already was "mixed". All implementations of the `SessionInterface` also use "mixed" as return type.

**Upgrade instructions**

Nothing to do

**Review instructions**

See current implementation of `TransientSession`: https://github.com/neos/flow-development-collection/blob/d14198d03d42a0f406565c50d85bcff6dad0f69e/Neos.Flow/Classes/Session/TransientSession.php#L132

**Checklist**

- [x] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked wit `!!!` and have upgrade-instructions

2023-06-01 12:42 UTC, robertlemke approved these changes
Makes sense!

2023-06-03 07:30 UTC, crydotsnake requested changes
Small nitpick.

2023-06-03 07:30 UTC, crydotsnake commented on Neos.Flow/Classes/Session/SessionInterface.php
>       * Returns the contents (array) associated with the given key.
```suggestion
     * Returns the content (mixed) associated with the given key.
```

2023-06-09 15:29 UTC, crydotsnake approved these changes

2023-08-05 08:52 UTC, merged