TASK: Revert "TASK: Avoid potential deprecation warning in StringHelper"
neos/flow-development-collection pull request #3167
Opened 2023-09-19 09:21 UTC by LvckyAPI

This reverts commit 1390d88103a6be6ddfa827eb834b0f666f5ea67b.

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked wit `!!!` and have upgrade-instructions

2023-09-19 09:56 UTC, mhsdesign commented
Thanks for reporting the issue and the fix ❤️ 

- what do you say @kdambekalns why dont we allow array? I must say i dont understand where any possible deprecation warning the method might be coming from, which you tried to fix with https://github.com/neos/flow-development-collection/pull/3117 ?
I guess you want to cast `int` to a string, but we need to preserve arrays as is?

2023-09-19 11:05 UTC, kdambekalns requested changes
_Oh my…_ PHP, you gotta love it. 😎

An array is allowed for search, replace – and subject, so **let's allow an array for the subject**, too. From https://www.php.net/str_replace:

>  If search and replace are arrays, then str_replace() takes a value from each array and uses them to search and replace on subject. If replace has fewer values than search, then an empty string is used for the rest of replacement values. If search is an array and replace is a string, then this replacement string is used for every value of search. The converse would not make sense, though.
>
> If search or replace are arrays, their elements are processed first to last. 
>
> If subject is an array, then the search and replace is performed with every entry of subject, and the return value is an array as well. 

But **if the passed valus are not array or string, we must cast to string** (most common case in Fusion/Eel is probably `null` coming in.)

2023-09-19 11:06 UTC, kdambekalns commented
Ah, and of course the return value can be an array, too. 🤪

2023-09-19 11:12 UTC, kdambekalns commented on Neos.Eel/Classes/Helper/StringHelper.php
>      public function replace($string, $search, $replace)
```suggestion
     * @param string|array $subject The input string|array
     * @param string|array $search A search string|array
     * @param string|array $replace A replacement string|array
     * @return string|array The subject with all occurrences replaced
     */
    public function replace($subject, $search, $replace)
    {
        if (!is_array($subject) && !is_string($subject)) {
            $subject = (string)$subject;
        }
        if (!is_array($search) && !is_string($search)) {
            $search = (string)$search;
        }
        if (!is_array($replace) && !is_string($replace)) {
            $replace = (string)$replace;
        }
```

2023-09-19 11:12 UTC, kdambekalns commented on Neos.Eel/Classes/Helper/StringHelper.php
> +        return str_replace($search, $replace, (string)$string);
```suggestion

        return str_replace($search, $replace, $subject);
```

2023-09-19 12:20 UTC, LvckyAPI commented
I will apply the requested changes from your review very soon.

Thank you :)

2023-09-19 12:43 UTC, LvckyAPI commented
I've implemented your suggestions @kdambekalns 
Thank you 😄

2023-09-19 19:02 UTC, mhsdesign approved these changes
Finde by 👀 

It should be actually quite easy to add a test case for this (there are unit tests already) - id really like that for the array case! ^^

2023-09-28 06:12 UTC, mhsdesign requested changes
I like https://github.com/neos/flow-development-collection/pull/3180 better because it has tests ^^

2023-09-28 06:37 UTC, kdambekalns commented
Thanks for bringing this up and proposing a PR – even though we merged a different one, don't give up! 😉

2023-09-28 06:37 UTC, closed without merging