FEATURE: Introduce EEL tracer for handling Neos9 deprecations
neos/flow-development-collection pull request #3386
Opened 2024-08-09 11:11 UTC by mhsdesign

In todays weekly @bwaidelich and me discussed a concrete way how to log deprecations like `node.indentifier` in Neos 8.4 and 9.0

The idea is to add a tracer to eel, that will be implemented in Fusion. Technically we would need to add an abstraction to Neos.Fusion as well to not access the Node from there as this is architecturally illegal but to simplify the code and in light that this is just considered for temporary time we propose to implement it as such:

```php
<?php

namespace Neos\Fusion\Core;

use Neos\Flow\Annotations as Flow;
use Psr\Log\LoggerInterface;

final class Neos9RuntimeMigrationTracer implements EelInvocationTracerInterface
{
    /** @Flow\Inject */
    protected LoggerInterface $logger;

    private const DEPRECATED_NODE_PROPERTIES = [
        'identifier' => true,
        'nodetype' => true,
        // ...
    ];

    public function __construct(
        private readonly string $eelExpression,
        private readonly bool $showMercy
    ) {
    }

    public function recordPropertyAccess(object $object, string $propertyName): void
    {
        if (
            $object instanceof \Neos\ContentRepository\Domain\Model\Node
            && array_key_exists(strtolower($propertyName), self::DEPRECATED_NODE_PROPERTIES)
        ) {
            $this->logDeprecationOrThrowException(
                sprintf('"node.%s" is deprecated in "%s"', $propertyName, $this->eelExpression)
            );
        }
    }

    public function recordMethodCall(object $object, string $methodName): void
    {
    }

    private function logDeprecationOrThrowException(string $message): void
    {
        if ($this->showMercy) {
            $this->logger->debug($message);
        } else {
            throw new \RuntimeException($message);
        }
    }
}
```

and instantiate this `Neos9RuntimeMigrationTracer` (name tbd) in `\Neos\Fusion\Core\Runtime::evaluateEelExpression`

```diff
- return EelUtility::evaluateEelExpression($expression, $this->eelEvaluator, $contextVariables);
+ $tracer =.$this->settings['enableDeprecationTracer'] ? new Neos9RuntimeMigrationTracer($expression, $this->settings['strictEelMode'] ?? false) : null;
+ return EelUtility::evaluateEelExpression($expression, $this->eelEvaluator, $contextVariables, $tracer);
```

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

2024-08-13 16:19 UTC, kitsunet requested changes
Before/after performance in a reasonably big site please ;) I think as small as this is, it will be a performance hit.

2024-08-14 07:54 UTC, mhsdesign commented
Of course if Fusion implements a stupid tracer that is way too slow by doing to many things there will be a performance hit, BUT as i have drawn out above we want to set the tracer fully to `null` in production and thus the optional chaining will just be a true noop:

```php
$this->tracer?->recordMethodCall($this->value, $method);
```

I also considered introducing some NoopTracer but that would be slower i guess.

2024-08-16 10:31 UTC, mhsdesign commented on Neos.Eel/Classes/EelInvocationTracerInterface.php
> +    public function recordMethodCall(object $object, string $methodName): void;
add recordFunctionCall and introduce arguments

2024-08-19 12:12 UTC, kitsunet approved these changes
Performance discussed, I am fine with that ✅

I woulnd't call it `showMercy`, but that is not part of this change so fine as the example :D 

I guess lets bring it in...

2024-09-12 14:13 UTC, merged